# Generated by Django 5.0.2 on 2024-02-27 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("actors", "0002_rename_nacionality_actor_nationality"),
        ("genres", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("resume", models.TextField(blank=True, null=True)),
                (
                    "actors",
                    models.ManyToManyField(related_name="movies", to="actors.actor"),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movies",
                        to="genres.genre",
                    ),
                ),
            ],
        ),
    ]
