# Generated by Django 5.0.2 on 2024-02-27 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("actors", "0002_rename_nacionality_actor_nationality"),
        ("genres", "0001_initial"),
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Movies",
            new_name="Movie",
        ),
    ]
